<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;DUQMQn47eCl7ImA9Wx5aFEw.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/1154/comments/full/1</ns0:id><ns0:author>
			<ns0:name>mseaborn@chromium.org</ns0:name><ns0:uri>/u/mseaborn@chromium.org/</ns0:uri></ns0:author><ns0:content type="html">Relevant Python bugs:
http://bugs.python.org/issue1199282 - error occurs in wait() (fixed)
http://bugs.python.org/issue1731717 - the more general case of the problem (still open)

gclient also hit this issue and applied the (sadly routine) workaround:
http://code.google.com/p/chromium/issues/detail?id=60623</ns0:content><ns0:updated>2010-11-10T19:29:43.000Z</ns0:updated><ns0:published>2010-11-10T19:29:43.000Z</ns0:published><ns2:updates>
			<ns2:ccUpdate>cbif...@google.com</ns2:ccUpdate></ns2:updates><ns0:title>Comment 1 by mseaborn@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1154#c1" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/1154/comments/full/1" rel="self" type="application/atom+xml" /></ns0:entry>