<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;AkYCRH47eCl7ImA9WhZRFUg.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/1636/comments/full/4</ns0:id><ns0:author>
			<ns0:name>mball@google.com</ns0:name><ns0:uri>/u/mball@google.com/</ns0:uri></ns0:author><ns0:content type="html">(CC khim)

Looks like the problem is that we've accidentally upgraded the python in hermetic cygwin to version 3.  Here are the two different python versions in the SDKs:

D:\src\native_client_sdk_0_1_721_0\third_party\cygwin\bin&gt;python.exe --version
Python 2.6.5

D:\src\native_client_sdk_0_2_781_0\third_party\cygwin\bin&gt;python.exe --version
Python 3.1.3

We'll need to either run that hideous 2to3 script, or go back to a previous version of hermetic cygwin.</ns0:content><ns0:updated>2011-04-11T21:42:45.000Z</ns0:updated><ns0:published>2011-04-11T21:42:45.000Z</ns0:published><ns2:updates>
			<ns2:ccUpdate>k...@google.com</ns2:ccUpdate></ns2:updates><ns0:title>Comment 4 by mball@google.com</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1636#c4" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/1636/comments/full/4" rel="self" type="application/atom+xml" /></ns0:entry>